### ISSUE TITLE
[QUEST] Liam's Fields

### ISSUE THREAD

**Issue by Ulfnaor** [AAGenesis/BugReports#101]
** Quest description **
Quest name: Liam's Fields
Zone, level: Solzreed Peninsula, 6.

**Describe the bug**
All the sheep start as shorn and do not seem to revert back.

**To Reproduce**
Log in, take a look at the field. 

**Expected behavior**
Sheep are supposed to revert back to normal (not shorn) as the quest asks you to either shear them or kill bees to complete. It is a minor annoyance.

**Additional context**
Speaking of bees, I don't know how possible to do so but there is only one in the entire field. Seeing as it is a "starter quest" and it requires you to kill at least five to complete it, you will want to add several extra bees (at least 4-5 extra). They're supposed to be there anyway.

**Comment by AAGene** [comment]
Issue fixed with system doodad timers. Bee issue will be looked at later with spawners.

**Comment by Ulfnaor** [comment]
New problem with it:

Shearing gives 10 points (as it should) but only does so once. Shearing extra sheeps doesn't seem to give any points towards the completion of the quest despite giving the "thick wool" necessary.

After further testing: the bug I just pointed above only happens if you try to shear the sheep twice (or more) in a row. If you shear a sheep, kill a bee and then shear again, the points are credited normally. If you shear several times in a row, the points aren't.

However, killing multiple bees in a row work, even if the number of bees is limited to one.
