### ISSUE TITLE
[QUEST] Feeding your Foal

### ISSUE THREAD

**Issue by Ulfnaor** [AAGenesis/BugReports#106]
** Quest description **
Quest name: Feeding your Foal
Zone, level:  Solzreed Peninsula, 7.

**Describe the bug**
I bring the package to Wyatt, the stablehand, who then gives me the quest "Feeding your Foal" whose objective is to plant a Vita Seed and then harvest it. However, he doesn't care once it is harvested and we thus cannot get a foal as step 2 remains elusive..

**To Reproduce**
1. Go to Wyatt.
2. Get Vita Seed and plant it.
3. Harvest Vita Seed for Vita Root and... watch Wyatt not give a fuck about it.

**Expected behavior**
Wyatt should reward your efforts by letting you pick a foal after you have harvested the Vita Root. He is operating at a loss and has perhaps noticed it.

I tried doing this quest about seven or eight times now. I tried purchasing vita seeds separately three times as well. It stays bugged.

**Comment by AAGene** [comment]
Should work better now.
