### ISSUE TITLE
[QUEST] Infected Warrens

### ISSUE THREAD

**Issue by Ulfnaor** [AAGenesis/BugReports#109]
** Quest description **
Quest name: Infected Warrens
Zone, level: Solzreed Peninsula, 8-9.

**Describe the bug**
The quest is asking me to use the quest's torch to set a haystack on fire by clicking on a rabbit's burrow. However, there is no haystack to be found. I'm almost certain this is due to the "quest not giving us more than one item" bug as the quest is supposed to give us both the torch (to set said hay on fire) and the haystack (to be set on fire).

**To Reproduce**
1. Go to some Farmer or another.
2. Get torch but no haystack. See haystacks you can't interact with because the game is trolly like that.
3. Walk around killing rabbits for shits and giggles as you desperately want to complete all quests but can't.
4. Report bug on github.

**Expected behavior**
If a bitch wants me to light her smoke, she should give me both the light and the cig, not just the light. What does he think I am, some kind of hay magician?

"Oh hi adventurer, do you per chance walk around with some fucking hay on you incase I want to burn down a rabbit hole?"

**Comment by AAGene** [comment]
Fixed with latest patch
