### ISSUE TITLE
[QUEST] Gwen Forest - A worthy opponent

### ISSUE THREAD

**Issue by SarielaGenesis** [AAGenesis/BugReports#138]
** Quest description **
Quest name: A Worthy Opponent
Zone, level: Gwen Forest

**Describe the bug**
You are supposed to pick up a blade and present it to a nuian knight to begin a duel. Upon presenting the blade, the fight auto completes and does not begin a duel with the knight, allowing you to turn in the quest.

**To Reproduce**
1. Pick up the blade
2. Go to nuian knight and present blade
3. Instead of dueling, the fight auto completes and is ready for turn in.

**Expected behavior**
Trial by combat

**Screenshots**
![worthy](https://user-images.githubusercontent.com/82345677/119018531-04dcc980-b951-11eb-9244-c91c327630c8.jpg)

**Additional context**

**Comment by ItzBoots** [comment]
Duplicate - See #18

**Comment by SarielaGenesis** [comment]
dupe!
