### ISSUE TITLE
[QUEST] Gwen Forest - Potent Pet Food

### ISSUE THREAD

**Issue by SarielaGenesis** [AAGenesis/BugReports#139]
** Quest description **
Quest name: Potent Pet Food
Zone, level: Gwen Forest

**Describe the bug**
When you deliver the foal to the stablehand he gives you a vita seed. When you plant the seed step 1 does not complete "plant a vita seed". Harvesting the seed did not advance anything either. Added a seed to my inv and planted and it worked and was able to complete quest.

**To Reproduce**
1. Turn in the foal
2. Plant received vita seed
3. Quest does not advance
4. /additem 23635 10
5. Plant Vita seed (now advances)
6. Harvest seed
7. Turn in and complete

**Expected behavior**
Should work from the quest given seed but does not

**Screenshots**

**Additional context**
I dont know if only having one seed in your inventory when planting makes a difference or not. Cant go back and retest. When i manually added 10 seeds it worked

**Comment by ItzBoots** [comment]
Duplicate - See #12

**Comment by SarielaGenesis** [comment]
updated 12 with new info and closing this one
