### ISSUE TITLE
[QUEST] Gwen Forest - The Flood Fanatic

### ISSUE THREAD

**Issue by SarielaGenesis** [AAGenesis/BugReports#141]
** Quest description **
Quest name: The flood fanatic
Zone, level: Gwen Forest

**Describe the bug**
You are supposed to use a key to unlock cages and release a prisoner. Prisoners are outside of their cages so you dont even need the key. You need to talk to all prisoners instead of one to complete the quest, not sure if it's due to them all being out of cages already or another quest bug.

**To Reproduce**
1. Go to break prisoner out of cage
2. See they are all already outside of their cages!
3. Notice that you have to talk to all prisoners instead of one as the quest says

**Expected behavior**
Open one cage, talk to one prisoner to complete.

**Screenshots**
![prisoner](https://user-images.githubusercontent.com/82345677/119025707-3ce80a80-b959-11eb-872c-2e5088a1756b.jpg)

**Additional context**

**Comment by ItzBoots** [comment]
Duplicate - See #41 & #11

**Comment by SarielaGenesis** [comment]
poop
