### ISSUE TITLE
[QUEST] Gwen Forest - Treacherous Waters

### ISSUE THREAD

**Issue by SarielaGenesis** [AAGenesis/BugReports#142]
** Quest description **
Quest name: Treacherous Waters
Zone, level: Gwen Forest

**Describe the bug**
Quest autocompletes and requests a bug report due to being sphered

**To Reproduce**
1. Accept the quest
2. Quest autocompletes and tells you to report it

**Expected behavior**
Swim across lake to fight the thing

**Screenshots**
![waters](https://user-images.githubusercontent.com/82345677/119026528-20000700-b95a-11eb-9a92-b6af1ec170ee.jpg)

**Additional context**

**Comment by ItzBoots** [comment]
Duplicate - See #10

**Comment by SarielaGenesis** [comment]
yes it is duplicate i delete thanks boots
