### ISSUE TITLE
[QUEST] Gwen Forest - Searching For Answers

### ISSUE THREAD

**Issue by SarielaGenesis** [AAGenesis/BugReports#145]
** Quest description **
Quest name: Searching For Answers
Zone, level: Gwen Forest

**Describe the bug**
When you use the detection orb on the field of honor participants, none of them ever turn red and attack you. Usually one will turn red and attack you.  Seems to have the same issue as the previous nuian knight quest where the battle just auto completes. Perhaps it's due to the strange roaming state they are in where they walk with idle animations? Not exactly a game breaking bug as you dont need to actually fight anyone. But if you are a perfectionist then there seems to be an issue there.

**To Reproduce**
1. Use the orb on field of honor participants
2. Again, no trial by combat

**Expected behavior**
Usually at least one turns red

**Screenshots**

**Additional context**

**Comment by ItzBoots** [comment]
Duplicate - See #19

**Comment by SarielaGenesis** [comment]
stop being mean to me boots
