### ISSUE TITLE
[STORY QUEST]Menacing Mushrooms

### ISSUE THREAD

**Issue by ItzBoots** [AAGenesis/BugReports#21]
** Quest description **
Quest name: Menacing Mushrooms
Zone, level: Gweonid Forest, Level 8
Quest ID: 2398

**Describe the bug**
[Quest Specific Dodad Issue]"Venomscale Mushroom" do not respawn, or have a very long respawn timer.(Waited 30 mins)

**To Reproduce**
1. Accept Quest "Menacing Mushrooms"
2. Pick a "Menacing Mushrooms"
3. Wait 30+ sec.

**Expected behavior**
Live servers have them respawn in around 30 sec.

**Screenshots**
None

**Additional context**
With long to no respawn timer, an a limited amount of mushrooms. roughly 3-5 people could progress through story quests.

**Comment by chaseymain** [comment]
Posted to new bug tracker. 

https://bt.aagenesis.xyz/view.php?id=38

**Comment by ItzBoots** [comment]
That is a Different Quest, with a Similar Bug.

This Issue has been resolved.
