### ISSUE TITLE
[SKILL] Resurgence and Antithesis (Almost all Vitalism skills)

### ISSUE THREAD

**Issue by Marvin732** [AAGenesis/BugReports#50]
**Skill description**
Skill Resurgence, Antithesis, Class Vitalism
**Describe the bug**
Disconnect from the server as soon as you want to cast the spell

**To Reproduce**
1. Cast Resurgence or Antithesis
2. See error

**Expected behavior**
Spell cast to heal/buff
**Screenshots**
https://www.youtube.com/watch?v=1L9sGL6RE60
**Additional context**

**Comment by Marvin732** [comment]
The only Skills so far not crashing the game are 
Twilight (doesnt add the buff for invisibility) 
Whirlwind Blessing
Skewer
Mend

**Comment by AAGenesis-Nova** [comment]
Fixed with latest patch.

Related to an issue with dungeons not handling object IDs properly so skills would break with invalid targets.
