### ISSUE TITLE
[QUEST] Planting Potatoes

### ISSUE THREAD

**Issue by Auxil3300** [AAGenesis/BugReports#6]
Quest name: planting potatoes
Zone: lilyut Hills 
Level: 15
Objective: Purchase a potato eye and plant it on the public farm
Desc: Planting the potato eye on the public farm does not give credit for the quest.

**Comment by Marvin732** [comment]
weirdly enough it seems like it has a connection to #12 , anything that has to do with gathering or planting wont complete, also i am able to keep planting the Potato eye even if you dont have the seeds in the inventory, just click on the little icon
![ScreenShot0019](https://user-images.githubusercontent.com/20370416/107863620-0f6d5b80-6e56-11eb-9dcc-2d3dedb4202d.jpg)
