### ISSUE TITLE
[SKILL] Double damage on fast click

### ISSUE THREAD

**Issue by mklozinski** [AAGenesis/BugReports#82]
**Skill description**
Seen on some ranged skills (bomb and 55skill)

**Describe the bug**
Sometimes, on spam clicking skills, they deals x2 damages. Skill is double casting with a difference of 1-5 ms.

**To Reproduce**
1.  Click as fast as possible on ranged bow skills that needs cast time

**Video**
https://www.youtube.com/watch?v=DbIW_IBQO3k

**Additional context**

**Comment by AAGene** [comment]
Fixed with SCD
