### ISSUE TITLE
[QUEST] Warming Up

### ISSUE THREAD

**Issue by ZeromusXYZ** [AAGenesis/BugReports#88]
** Quest description **
Quest name: Warming Up
Zone, level: Falcorth starter quests

**Describe the bug**
Upon completion of killing the foxes, it displays 0/3 instead of 3/3, but does complete to the next phase correctly

**To Reproduce**
1. Start quest
2. Kill 3 foxes

**Expected behavior**
That it displays 3/3 kills before moving to the next phase

**Screenshots**
https://mega.nz/file/DvJWCTyJ#Kv1SOM-_HqGhN7N1vghW8hueEwr7ALNXbB4vzV8st50

**Additional context**
None.

**Comment by AAGene** [comment]
Quest progress is now displayed as it goes
