### ISSUE TITLE
[QUEST] The Friendly Feline

### ISSUE THREAD

**Issue by ItzBoots** [AAGenesis/BugReports#96]
** Quest description **
Quest name: The Friendly Feline
Zone, level: Gweonid, Level 5
Quest ID: 97

**Describe the bug**
When completing quest, you only receive the Elven Sword. You don't get the Elven Nodachi or Elven Staff.

**To Reproduce**
1. Accept Quest
2. Turn In Quest
3. See error

**Expected behavior**
Receive Elven Sword, Elven Nodachi, An Elven Staff.

**Screenshots**
https://prnt.sc/12vut6m
https://prnt.sc/12vuu7f

**Additional context**
None

**Comment by AAGene** [comment]
Works as expected
