### ISSUE TITLE
[QUEST] Wing Delivery

### ISSUE THREAD

**Issue by ItzBoots** [AAGenesis/BugReports#98]
** Quest description **
Quest name: Wing Delivery
Zone, level: Gweonid, Level 5
Quest ID: 1641

Describe the bug
When completing quest, you only receive the Elven Bow. You don't get the Elven Shield, Elven Lute, or Elven Greatclub.

**To Reproduce**
1. Accept Quest
2. Turn In Quest
3. See error

**Expected behavior**
Receive Elven Bow, Shield, Lute, and Greatclub

**Screenshots**
https://prnt.sc/12vv08x
https://prnt.sc/12vv5sb

**Additional context**
None

**Comment by ItzBoots** [comment]
Similar Issue to #96

**Comment by AAGene** [comment]
Works as expected

**Comment by Ulfnaor** [comment]
Velpo's Victims and A Guiding Light are the Nuian version of those two quests and also only give one item instead of the supposed four.
